### ISSUE TITLE
useNavigate() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by mixmaker** [frontend-joe/react-wavy-transitions#9]
when using WavyLink conponent I got this error
`
useNavigate() may be used only in the context of a <Router> component.
    at invariant (http://localhost:3000/static/js/bundle.js:6480:11)
    at useNavigateUnstable (http://localhost:3000/static/js/bundle.js:115652:102)
    at useNavigate (http://localhost:3000/static/js/bundle.js:115649:46)
    at WavyLink (http://localhost:3000/static/js/bundle.js:116954:50)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:49684:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:52970:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:54266:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:39276:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:39320:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:39377:35)
`

**Comment by mixmaker** [comment]
React-router-dom & react-wavy-transitions were using two different versions of react-router caused the issue

├─┬ react-router-dom@6.11.0
│ └── react-router@6.11.0
└─┬ react-wavy-transitions@1.1.1
  └─┬ react-router-dom@6.11.1
    └── react-router@6.11.1

for reference:
https://github.com/remix-run/react-router/issues/8701#issuecomment-1066219658
